title: Raccoon's Trash Can
description: Hi! I’m a raccoon, and this is my trash can :] It’s full of my thoughts about the mess of being human. No human is perfect, including me, and that’s why we are so fascinating.
theme: null
url: "https://raccoonfangz.github.io"
plugins:
  - jekyll-feed
